// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SourcingAPI.Data;

#nullable disable

namespace SourcingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SourcingAPI.Models.SourcingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuyerCST")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Commodity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CostingSheet")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrawingRevision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DualSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsirDocuments")
                        .HasColumnType("boolean");

                    b.Property<bool>("PpapDocument")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaReleasedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SapCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolCostStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sourcinghandover");
                });
#pragma warning restore 612, 618
        }
    }
}
